### ISSUE TITLE
KYC-Match: Clarification on handling of unsupported attributes?

### ISSUE THREAD

**Issue by scarrk** [camaraproject/KnowYourCustomer#168]
What would be the expected response from the MNO when a request includes attributes (such as gender, email) in a KYC Match request, that are not supported?

1) For the attributes that are not supported, you return a 'not_available' in the response (rather than true, false)
2) You return an Error 400 InvalidArgument"
3) Other

Appreciate feedback from the community on how your implementations handle the above scenario.

**Comment by GillesInnov35** [comment]
hi @scarrk, at Orange when a request includes attributes which belongs to the properties of the API but not supported by the MNO API, a matchResult is returned with "not_available". This is also what has been decided by the KYC project contributors.
BR
Gilles

**Comment by HuubAppelboom** [comment]
Hi @scarrk @GillesInnov35 Currently at KPN we provide a "not_available" if one ore more of the attributes is not available. This way you can still provide as much as possible market reach (and some items we have poor coverage, like gender etc.).   In case there is no data at all available,. it may be better to provide an error code (otherwise you have to analyse the result that has been returned whether or not data has been available). Working with an error code may be simpler.  On the other hand, if you want to charge based on what has been asked, you will need to do just that.  So, there is also a connection here with what you want to charge.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @scarrk , 

> 1. For the attributes that are not supported, you return a 'not_available' in the response (rather than true, false)


As Gilles mentioned, this is what we have decided.  Originally it was captured in Issue #21 KYC Match - Match Result Response (for v0.1) , and also in Issue #85 [KYC Match] Scoring (no change confirmed for v0.2)  .

Thanks.
Toshi

**Comment by claraserranosolsona** [comment]
Hi @scarrk ,

As Gilles and Toshi mentioned, for the attributes that are not supported we return a 'not_available' in the response (rather than true, false)

Regards,
Clara

**Comment by KevScarr** [comment]
@GillesInnov35 @HuubAppelboom @ToshiWakayama-KDDI @claraserranosolsona Many thanks all for the clarification.
Happy for this item to be closed off.

**Comment by ToshiWakayama-KDDI** [comment]
Closed, as the issue has been cleared.
