### ISSUE TITLE
CHANGELOG.MD

### ISSUE THREAD

**Issue by GillesInnov35** [camaraproject/KnowYourCustomer#40]
add Changelog.md to the API project repo.

[CHANGELOG.MD](https://github.com/camaraproject/KnowYourCustomer/files/13888894/CHANGELOG.MD)

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @GillesInnov35 ,

Slight changes were made, as we have embedded API Documentation into the YAML files. 

[CHANGELOG_v24-02-17.MD](https://github.com/camaraproject/KnowYourCustomer/files/14317756/CHANGELOG_v24-02-17.MD)

If there should be any further changes, please let us know.  Otherwise, I will upload this to the API project repo.

Thanks.
Toshi

**Comment by GillesInnov35** [comment]
Thanks @ToshiWakayama-KDDI 
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Closed as the issue was solved.
